name: CI

on:
  push:
    branches:
      - master
    tags: ['v*']
  pull_request:
    branches:
      - master


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        pytest: ["pytest>=8.0,<8.1", "pytest>=8.1,<8.2", "pytest>=8.2,<8.3", "pytest>=8.3,<8.4", "pytest>=9.0,<9.1"]

    env:
      UV_EXTRA_ARGS: --with "${{ matrix.pytest }}"

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: astral-sh/setup-uv@v7
    - run: echo ${{ matrix.python }} > .python-version
    - run: make deps
    - run: make lint MODE=ci
    - run: make test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: astral-sh/setup-uv@v7
    - run: uv build
    - env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: uv publish
